name: tiutiu
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter_localizations: 
    sdk: flutter
  flutter:
    sdk: flutter

  flutter_local_notifications: ^12.0.4
  mask_text_input_formatter: ^2.4.0
  flutter_native_splash: ^2.0.0
  flutter_facebook_auth: ^5.0.6
  font_awesome_flutter: ^10.2.1
  flutter_screenutil: ^5.5.3+2
  cached_network_image: ^3.2.1
  flutter_chat_bubble: ^2.0.0
  shared_preferences: ^2.0.15
  permission_handler: ^10.0.0
  sign_in_with_apple: ^4.1.0
  loading_animations: ^2.2.0  
  flutter_speed_dial: ^6.0.0  
  move_to_background: ^1.0.2
  connectivity_plus: ^2.3.7    
  google_mobile_ads: ^2.3.0
  package_info_plus: ^1.0.0
  device_info_plus: ^8.0.0
  webview_flutter: ^4.0.6
  pin_code_fields: ^7.4.0
  flutter_pdfview: ^1.2.5
  carousel_slider: ^4.0.0  
  cupertino_icons: ^1.0.5
  auto_size_text: ^3.0.0
  google_sign_in: ^5.4.2
  image_picker: ^0.8.5+3
  open_settings: ^2.0.2
  screenshot: ^1.3.0
  better_player:
    git:
      url: https://github.com/AndreDrummer/betterplayer.git
      ref: fix-android-and-ios
  maps_launcher: ^2.0.1
  brasil_fields: ^1.6.0  
  google_fonts: ^3.0.1
  url_launcher: ^6.1.5
  share_plus: ^6.3.0
  geolocator: ^9.0.1
  geocoding: ^2.0.5    
  provider: ^6.0.3
  sqflite: ^2.0.3
  lottie: ^2.2.0
  video_player:
  uuid: ^3.0.6
  get: ^4.6.5  
  pdf: ^3.8.4
  dio: ^4.0.6
  intl: any    
  chewie:

  firebase_core_platform_interface: 4.5.2
  firebase_dynamic_links: ^5.0.8
  firebase_crashlytics: ^3.0.9
  firebase_analytics: ^10.0.7
  firebase_messaging: ^14.1.4
  firebase_database: ^10.0.7
  firebase_storage: ^11.0.7
  cloud_firestore: ^4.2.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0

flutter_icons:
  image_path: "assets/images/ios_icon_dark.png"
  # when generating icon for Android uncomment the next two lines and comment the two lines right below them.
  # android: "launcher_icon"
  # ios: false
  android: false
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.11.0
  pedantic: any

flutter:
  uses-material-design: true  
  generate: true
  assets:    
    - assets/startscreen/
    - assets/animations/
    - assets/images/
    - assets/json/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
